// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMfb_Hyd5k9L89SQPWn1RweCqPQ-wgzXc',
    appId: '1:28592004839:web:685c9b1df856e31e670c42',
    messagingSenderId: '28592004839',
    projectId: 'foodai12',
    authDomain: 'foodai12.firebaseapp.com',
    storageBucket: 'foodai12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXUDUeKbigrSH9yZOgn4xWEnAA4peeWmA',
    appId: '1:28592004839:android:a7fb2176174366d1670c42',
    messagingSenderId: '28592004839',
    projectId: 'foodai12',
    storageBucket: 'foodai12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0InA8aHFH4yGT3EMzFqjySInSM4c9s28',
    appId: '1:28592004839:ios:a9b28966365c429f670c42',
    messagingSenderId: '28592004839',
    projectId: 'foodai12',
    storageBucket: 'foodai12.firebasestorage.app',
    iosBundleId: 'com.example.foodai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0InA8aHFH4yGT3EMzFqjySInSM4c9s28',
    appId: '1:28592004839:ios:a9b28966365c429f670c42',
    messagingSenderId: '28592004839',
    projectId: 'foodai12',
    storageBucket: 'foodai12.firebasestorage.app',
    iosBundleId: 'com.example.foodai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMfb_Hyd5k9L89SQPWn1RweCqPQ-wgzXc',
    appId: '1:28592004839:web:c2df80120493e1c7670c42',
    messagingSenderId: '28592004839',
    projectId: 'foodai12',
    authDomain: 'foodai12.firebaseapp.com',
    storageBucket: 'foodai12.firebasestorage.app',
  );
}
